version: 2.0
jobs:
  build-german:
    working_directory: ~/websites/john-website-deutsch
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/websites
      - run:
          name: Echo branch
          command: echo ${CIRCLE_BRANCH}
      - restore-cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install local dependencies
          command: |
            npm i @angular/cli
            npm install;
            npm rebuild node-sass
      - save-cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building
          command: npm run build-prod
      - save_cache:
          key: v1-dist-german-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  build-english:
    working_directory: ~/john-website-english
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Echo branch
          command: echo ${CIRCLE_BRANCH}
      - restore-cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install local dependencies
          command: npm install
      - save-cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building
          command: npm run build-prod
      - save_cache:
          key: v1-dist-english-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          path:
            - dist

  deploy-german:
    working_directory: ./
    machine:
      image: circleci/classic:lastest
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - restore-cache:
          key: v1-dist-german-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Send German Via SFTP
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v -R dist /home/john/htdocs"


workflows:
  version: 2

  build-german_and_deploy-german:
    jobs:
      - build-german
#      - deploy-german:
#          requires:
#            - build-german