version: 2.0
jobs:
  download-dependencies:
    working_directory: ~/websites/john-website-deutsch
    docker:
        - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/websites
      - restore-cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: npm install;
      - save-cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  build-german:
    working_directory: ~/websites/john-website-deutsch
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/websites
      - run:
          name: Echo branch
          command: echo ${CIRCLE_BRANCH}
      - restore-cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Building
          command: npm run build-prod
      - run:
          name: Copy sitemap
          command: cp src/sitemap*.xml dist/john-website
      - save_cache:
          key: dist-german-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  build-english:
    working_directory: ~/websites/john-website-english
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/websites
      - run:
          name: Echo branch
          command: echo ${CIRCLE_BRANCH}
      - restore-cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Building
          command: npm run build-prod
      - run:
          name: Copy sitemap
          command: cp src/sitemap*.xml dist/john-website
      - save_cache:
          key: dist-english-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy-german:
    working_directory: ./websites/john-website-deutsch
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - restore-cache:
          key: dist-german-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Save all non angular files
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v --exclude '.*\.js' --exclude '.*\.css' --exclude '.*\.html' --exclude 'assets\/.*' --include 'en\/' /home/john/htdocs/johnlouisjacobs.de dist/john-website; quit"
      - run:
          name: Show downloaded files
          command: ls dist/john-website
      - run:
          name: Send German Via SFTP
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v -R --delete-first dist/john-website /home/john/htdocs/johnlouisjacobs.de; quit"

  deploy-english:
    working_directory: ./websites/john-website-english
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - restore-cache:
          key: dist-english-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Save all non angular files
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v --exclude '.*\.js' --exclude '.*\.css' --exclude '.*\.html' --exclude 'assets\/.*' /home/john/htdocs/johnlouisjacobs.de/en dist/john-website; quit"
      - run:
          name: Show downloaded files
          command: ls dist/john-website
      - run:
          name: Send German Via SFTP
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v -R --delete-first dist/john-website /home/john/htdocs/johnlouisjacobs.de/en; quit"

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - download-dependencies
      - build-german:
          requires:
            - download-dependencies
      - deploy-german:
          requires:
            - build-german

      - build-english:
          requires:
            - download-dependencies
      - deploy-english:
          requires:
            - build-english