version: 2.0
jobs:
  build-german:
    working_directory: ~/websites/john-website-deutsch
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/websites
      - run:
          name: Echo branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show Nodeversion
          command: node -v
      - restore-cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install local dependencies
          command: |
            npm install;
      - save-cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building
          command: npm run build-prod
      - save_cache:
          key: v1-dist-german-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  build-english:
    working_directory: ~/websites/john-website-english
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/websites
      - run:
          name: Echo branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show Nodeversion
          command: node -v
      - restore-cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install local dependencies
          command: |
            npm install;
      - save-cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building
          command: npm run build-prod
      - save_cache:
          key: v1-dist-english-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy-german:
    working_directory: ./websites/john-website-deutsch
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - restore-cache:
          key: v1-dist-german-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Download all non angular files
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v --exclude '.*\.js' --exclude '.*\.css' --exclude '.*\.html' --exclude 'assets\/.*' --include 'en\/' /home/john/htdocs/johnlouisjacobs.de dist/john-website; quit"
      - run:
          name: Show downloaded files
          command: ls dist/john-website
      - run:
          name: Send German Via SFTP
          command: lftp sftp://${username}:${password}@${hostname} -e "mirror -v -R --delete-first dist/john-website /home/john/htdocs/johnlouisjacobs.de; quit"


workflows:
  version: 2

  build-german_and_deploy-german:
    jobs:
      - build-german
      - deploy-german:
          requires:
            - build-german